<?php

namespace app\components;

use yii\base\Widget;
use app\models\Category;
use Yii;
//виджет отчечает за построение меню
class MenuWidget extends Widget
{
    public $tpl; //режим отображанеия меню горизонтальное или вертикальное (0,1)
    public $data; //хранятся все записи категорий из БД
    public $tree;  //дерево значений для категорий товаров и их подкатегорий
    public $menuHtml; //созданное меню
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if($this->tpl != 'select'){
            $this->tpl = 'menu';
        }

        $this->tpl .= '.php';
    }

    public function run()
    {
        if($this->tpl == 'menu.php'){

            $menu = Yii::$app->cache->get('menu');

            if($menu){
                return $menu;
            }
        }

        $this->data = Category::find()->indexBy('id')->asArray()->all(); //получаем список категорий товаров
        $this->tree = $this->getTree(); //строим дерево

        //рекурсивно строим меню с неограниченным количеством подкатегорий
        $this->menuHtml = '<ul class="catalog category-products">';
        $this->menuHtml .= $this->getMenuHtml($this->tree);
        $this->menuHtml .= '</ul>';

        if($this->tpl == 'menu.php'){
            Yii::$app->cache->set('menu', $this->menuHtml, 60);
        }

        return $this->menuHtml;

    }

    protected function getTree(){
        $tree = [];

        foreach($this->data as $id=>&$node){
            if(!$node['parent_id']){
                $tree[$id] = &$node;
            }
            else{
                $this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
            }
        }
        return $tree;
    }

    protected function getMenuHtml($tree, $tab = ''){
        $str = '';
        foreach($tree as $category){
            $str .= $this->catToTemplate($category, $tab);
        }
        return $str;
    }

    protected function catToTemplate($category, $tab){
        ob_start();
        include __DIR__ . '/menu_tpl/' . $this->tpl;
        return ob_get_clean();
    }
}



























